### PR TITLE
Indi pentax

### PR DESCRIPTION
**Pull request by Graf2242**
There are two fixes to indi-pentax driver for k20d:
 - "Bad file descriptor" fix
 As mentioned here - https://github.com/indilib/indi-3rdparty/issues/775 - there are many errors in logs if driver can't connect to camera. I'm not sure that i implement fix right, but at least it's working

- Pentax K20d fix
https://github.com/indilib/indi-3rdparty/blob/master/indi-pentax/pktriggercord_ccd.cpp#L856 . If driver can't identify any of device batteries - it just disconnect. I tried to parse state hexdump and seem that 0x168 is correct address. I have no battery grip so I can't check it's state address 

To be fair, there are two more fixes need for k20d to work:
 - As mentioned here - https://github.com/indilib/indi-3rdparty/issues/775#issuecomment-2123855267 - I had to comment out PTP mode (othervise driver stuck somewhere near https://github.com/indilib/indi-3rdparty/blob/master/indi-pentax/indi_pentax.cpp#L62)
 - PkTriggerCord uses raw ioctl here - https://github.com/indilib/indi-3rdparty/blob/913c233635f4af305461442bc079c19db1a5872d/libpktriggercord/src/pslr_scsi_linux.c#L212 - and for now it requires root permissions. Workaround is execute this command once after install/upgrade driver (not sure at all how to do it properly)
 `setcap cap_sys_rawio+ep /usr/bin/indi_pentax`

### CODE REVIEW

**Comment by knro** [comment]
Thank you! @karlrees Can you please review this?

**Comment by Graf2242** [comment]
Also had to up cmake_minimum_required to 3.19 otherwise I got this warning. It's almost 4 years old, shouldn't be a problem I hope.

`CMake Warning (dev) at CMakeLists.txt:51 (find_program):
  Policy CMP0109 is not set: find_program() requires permission to execute
  but not to read.  Run "cmake --help-policy CMP0109" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The file

    /usr/bin/sudo

  is executable but not readable.  CMake is ignoring it for compatibility.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:51 (find_program):
  Policy CMP0109 is not set: find_program() requires permission to execute
  but not to read.  Run "cmake --help-policy CMP0109" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The file

    /usr/bin/sudo

  is executable but not readable.  CMake is ignoring it for compatibility.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:53 (message):
  sudo must be available on the system in order to set permissions for the
  driver`

**Comment by knro** [comment]
Can you please bump the version and update the corresponding [Debian changelog](https://github.com/indilib/indi-3rdparty/blob/master/debian/indi-pentax/changelog)?

**Comment by Graf2242** [comment]
> Can you please bump the version and update the corresponding [Debian changelog](https://github.com/indilib/indi-3rdparty/blob/master/debian/indi-pentax/changelog)?

Done. Never did it before, tbh. Hope it's right

**Comment by karlrees** [comment]
I had worked out a supposed fix to the bad file descriptor issue as well, though my solution was different.  My solution worked on some platforms (e.g., my Astroberry install), but not Ubuntu 23.10 or 24.04 with the Raspberry Pi 5.  Due to lack of time, I ended up dropping the issue for a while.  Anyway, I just tested your solution on Ubuntu 24.04 with the Raspberry Pi 5, and the error remains for me.  What platform were you working on?

**Comment by Graf2242** [comment]
I have only AMD64 Gentoo for now and checked fix on Arch VM also. Will try to install ubuntu 24.04 VM today and check this out (and unfortunately still have no raspberry to test Astroberry)

**Comment by Graf2242** [comment]
Well, it's work for me on Ubuntu 24.04, here are couple screenshots
image
image
And one shot before fixes:
image

Also looks like for ubuntu setcap fix for indi_pentax is not required, it's enough to update libpktriggercord only (but maybe it's some VM stuff)

**Review by karlrees — APPROVED** [review]
These commits do not cause any regression for me, so I am okay with them.  They do not appear to fix the problem on any of the Raspberry Pi 5 installations I have tested, so there is probably more to the issue, but if they help some people, I have no problem with them.

**Comment by karlrees** [comment]
@knro I have a fix for all of my Raspberry Pi installations.  It's in my fork (https://github.com/karlrees/indi-3rdparty).  It's possible that there are two distinct issues and both Graf2242's fix and my fix are needed.  I'm not too savvy on best development practices--should I be submitting my fixes as a separate pull request, or somehow combining them with this pull request?  

(Full disclosure, I also made a couple of other changes to the driver to support DNG files better, possibly support K3-III, and sync the pktriggercord source to its latest version).

**Comment by Graf2242** [comment]
> should I be submitting my fixes as a separate pull request, or somehow combining them with this pull request?

I'm totally fine with both ways. Probably at least we should merge both fixes for Debian single release. Better ask @knro for how to do it better (I can cherry-pick karlrees's fixes in my branch, for example)

**Comment by knro** [comment]
@Graf2242 If you can cherry pick @karlrees fixes that would great!

**Comment by Graf2242** [comment]
So, I did merged our fixes together:
- throw away my "Bad descriptor" fis as karlrees's works for me too (thank you!)
- merge other fixes together
- edit debian changelogs (again: did it first time. Please check if I did it right)

**Comment by Graf2242** [comment]
```
[ 63%] Building C object libpktriggercord/CMakeFiles/pktriggercord.dir/libpktriggercord.c.o
/__w/indi-3rdparty/indi-3rdparty/build/indi-3rdparty-libs/libpktriggercord/libpktriggercord.c:70:28: error: 'longopts' defined but not used [-Werror=unused-const-variable=]
   70 | static struct option const longopts[] = {
      |                            ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [libpktriggercord/CMakeFiles/pktriggercord.dir/build.make:76: libpktriggercord/CMakeFiles/pktriggercord.dir/libpktriggercord.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1054: libpktriggercord/CMakeFiles/pktriggercord.dir/all] Error 2
```
Well, I'll comment out [this](https://github.com/indilib/indi-3rdparty/pull/936/files#diff-feb7b6bd0622a18200e054de6935b0cab65f680a4e43032c3a3bc089f0c78251L67) again tomorrow if no one stops me

**Comment by karlrees** [comment]
@Graf2242 

The version needs to be changed in the CMakeLists.txt files for both indi_pentax (line 10, INDI_PENTAX_VERSION_MINOR) and libpktriggercord (line 4, PK_VERSION) as well.  Looks like I changed these before without updating the DEBIAN changelog.  To be consistent, we probably should bump the version for indi_pentax to 1.2, and the version for libpktriggercord to 85.03.

**Comment by Graf2242** [comment]
> To be consistent, we probably should bump the version for indi_pentax to 1.2, and the version for libpktriggercord to 85.03.

Yep, good point. Done

**Pull request merged**
