### PR TITLE
Fix some issues with the last QHY driver

### PR DESCRIPTION
**Pull request by sonny486**
Found some issues that I corrected.

### CODE REVIEW

**Comment by knro** [comment]
Did you check my changes?

**Comment by sonny486** [comment]
I didn't see them, sorry.

**Comment by sonny486** [comment]
I noticed the cap variable may have had an issue due to me doing cap = CCD_CAN_BIN 4 times

**Comment by knro** [comment]
Check my changes and see if these work for you.

**Comment by sonny486** [comment]
But I did compile after the pull was done to check, and CCD_CAN_SUBFRAME wasn't working in the full compile.

I didn't see what the changes were, but I know the compile wasn't showing ABORT nor SUBFRAME in capabilities.

**Pull request closed without merging**
