### PR TITLE
Added indi_rpicam (a.k.a indi_raspistill)

### PR DESCRIPTION
**Pull request by lboclboc**
This is my driver for the RPI 12MPX Hi-Quality camera that came out recently.
(used to live here: https://github.com/lboclboc/indi_raspistill but I will drop that)

### CODE REVIEW

**Comment by knro** [comment]
Great, can you please include the Debian files as well? Just start from any of the drivers and use that as a template. Is mmal package available on raspberry pi? or do we need to add it also here?

**Comment by knro** [comment]
Thanks, this is good to go! Final part is documentation, can you please prepare documentation we can add for this driver in INDI website? You can use [the camera documentation template](https://github.com/indilib/indi/tree/master/drivers) as a starting point.

**Comment by lboclboc** [comment]
> Thanks, this is good to go! Final part is documentation, can you please prepare documentation we can add for this driver in INDI website? You can use [the camera documentation template](https://github.com/indilib/indi/tree/master/drivers) as a starting point.

Thanks, I have the documentation here now: https://github.com/lboclboc/indi_raspistill/tree/master/docs

**Comment by knro** [comment]
Thank you!! It's added now to the official website!

**Pull request merged**
