### PR TITLE
Indi WeeWX JSON

### PR DESCRIPTION
**Pull request by rickbassham**
# WeeWX JSON Driver

This driver uses the [WeeWX JSON](https://github.com/teeks99/weewx-json) plugin to provide weather data to INDI.

### CODE REVIEW

**Comment by knro** [comment]
Awesome driver thanks, this would make a lot of weather stations now available to INDI via WeeWX!

**Comment by knro** [comment]
Thanks, can you please submit driver documentation in INDI Website as well?

**Comment by rickbassham** [comment]
> Thanks, can you please submit driver documentation in INDI Website as well?

Will do.

**Comment by knro** [comment]
Debian files are missing and without them, we cannot add to PPA.

**Comment by rickbassham** [comment]
@knro is this being built in the PPA yet?

**Comment by knro** [comment]
@rickbassham Nope sorry not yet. Can I ask for your help with this? I can add you to launchpad team to manage the PPA builds.

**Comment by rickbassham** [comment]
@knro Sure. I've never worked in launchpad, but it shouldn't be too difficult to figure out.

**Pull request merged**
