### PR TITLE
Interferometer

### PR DESCRIPTION
**Pull request by iliaplatone**
Here I fixed plotting of the baselines in the final image

### CODE REVIEW

**Comment by knro** [comment]
Let me know once this PR is ready to land

**Comment by iliaplatone** [comment]
Not yet ready

**Comment by iliaplatone** [comment]
Now it is ready, I have to write some docs into its repo and start to write also on the work of these months

**Comment by iliaplatone** [comment]
@knro you can merge if correct

**Comment by knro** [comment]
Thank you, really looking forward to the documentation and guides for at least amateur radio astronomers!

**Pull request merged**
