### PR TITLE
Svbony sdk update to 1.13.2

### PR DESCRIPTION
**Pull request by jctk**
Update SVBONY SDK to 1.13.2
* Support new camera SV905C2, SV305C Pro
* Fixup ASCOM software to support SV905C2 and SV305C Pro cameras
* Fixup exposure time of SV905C2
* Optimize gain settings of SV905C2

### CODE REVIEW

**Comment by jctk** [comment]
Hi @knro ,
It seems that this RP is not reflected in master.
Could you please confirm that?

image

**Comment by knro** [comment]
It's merged already. You are seeing CI errors which you can ignore.

**Comment by jctk** [comment]
From your environment, have you confirmed that this PR has been committed to GitLab master?

On my PC, I have confirmed in the indi-3rdparty repository in GitLab that this PR was not committed on December 30 when it was merge.
image

The last commit of the bin file in the master branch of libsvbony was 7 months ago as shown in the screenshot below.
The commit message says Version 1.12.8, which is different from PR's 1.13.2.
image

**Comment by knro** [comment]
You are correct!! I think a force push might have deleted it. Can you please resubmit again?

**Comment by jctk** [comment]
I have recommited the PR as #1021.

Note:
There seems to be another missing commit besides PR #1015.
For example, #1014 is also missing.

**Pull request merged**
