### PR TITLE
add & update Touptek and oem lib, version:53.22081.20230207

### PR DESCRIPTION
**Pull request by touptek**

### CODE REVIEW

**Comment by knro** [comment]
Thanks, you need to run 

**dos2unix** 

On all non-binary files to convert them to UNIX end of line. Is it possible to unify all OEMs into a single library rather than multiple libraries like it is now? This would make it so much simpler to maintain and will remove any duplication of code that is not really necessary.

**Comment by touptek** [comment]
> Thanks, you need to run
> 
> **dos2unix**
> 
> On all non-binary files to convert them to UNIX end of line. Is it possible to unify all OEMs into a single library rather than multiple libraries like it is now? This would make it so much simpler to maintain and will remove any duplication of code that is not really necessary.



> Thanks, you need to run
> 
> **dos2unix**
> 
> On all non-binary files to convert them to UNIX end of line. Is it possible to unify all OEMs into a single library rather than multiple libraries like it is now? This would make it so much simpler to maintain and will remove any duplication of code that is not really necessary.

dos2unix: ok
It's not possible to unify oem to single binary. It's about business, developers can't make the decisions.

**Comment by touptek** [comment]
awaiting approval to check

**Comment by touptek** [comment]
Please approval to check

**Comment by sonny486** [comment]
Great to see you guys working on these!  Thank you.

-Sonny

**Comment by touptek** [comment]
Please approval to check

**Comment by sonny486** [comment]
@knro will review and commit.

**Comment by knro** [comment]
There are still CI errors. Are you building locally @touptek ?

**Comment by touptek** [comment]
> @touptek Looks like the build is missing bressercam.h in the CI library. You may have it on your local machine, but the CI compiler cannot find it. I do see libbressercam.h but not bressercam.h

In the build log:
747  -- Installing: /usr/local/include/libbressercam/bressercam.h

I really can't figure it out

**Comment by touptek** [comment]
> There are still CI errors. Are you building locally @touptek ?

Sorry, this is my first time working on a project on GitHub. I don't know how to build locally, shy

**Comment by knro** [comment]
Ok @touptek I found the issues and was able to build successfully locally. Please check the attached patch.
[toupcam.txt](https://github.com/indilib/indi-3rdparty/files/10712866/toupcam.txt)

**Comment by touptek** [comment]
> Ok @touptek I found the issues and was able to build successfully locally. Please check the attached patch. [toupcam.txt](https://github.com/indilib/indi-3rdparty/files/10712866/toupcam.txt)

After this pull requst, I'm going to start the code

**Pull request merged**
