### PR TITLE
BUGFIX: indi_sv305_ccd: garbage data in last line (Issue #654)

### PR DESCRIPTION
**Pull request by jctk**
- In sv305_ccd.cpp, I implemented a process to get the ROI actually set by SVBGetROIFormat.
- After setting the ROI with SVBSetROIFormat, I need to get the actual ROI with SVBGetROIFormat, because the ROI obtained with SVBGetROIFormat may differ from the value specified with SVBSetROIFormat.
- Issue #654 was raised because this feature was not implemented.

### CODE REVIEW

**Comment by jctk** [comment]
Hi, @knro 
I would like to know how to set values for Frame X: Y: Size Width: Height: in Ekos. This is to reflect the correct ROI.

Top Left Width Height in INDI Control Panel can be set by member functions of CCD or by `CCD_FRAME` in Standard Properties.
These methods cannot be reflected in Ekos.

image

By the way, when I changed the Height in the INDI Control Panel on the ASI CCD, it was not reflected in Ekos.
Is there any way to set this in Ekos?

**Comment by knro** [comment]
Thanks, this is not an INDI issue, but it appears you're using a slightly older version of KStars? have you tried 3.6.0 stable or beta 3.6.1 ?

**Comment by jctk** [comment]
I am using KStars 3.6.0 Stable.
I have tested KStars on Windows 11 and StellarMate OS.

**Comment by jctk** [comment]
The screenshots are transcribed from the kStars website.

**Comment by knro** [comment]
Ah okay, the screenshots are out of date. At any rate, the ROI in Ekos reflects *target* setting and not necessary current camera settings.

**Comment by jctk** [comment]
Thanks for the review and merge.
I understand that the ROI for Ekos is target setting.

**Pull request merged**
