### PR TITLE
Fix data pile-up in gpsd

### PR DESCRIPTION
**Pull request by jochym**
Empty the buffer of gpsd daemon and keep just last segment of data. Fix suggested by @rtlprmft in https://github.com/indilib/indi-3rdparty/issues/180

### CODE REVIEW

**Comment by knro** [comment]
Excellent. I guess there is no way for the while loop to get stuck under any circumstance?

**Comment by jochym** [comment]
That is my worry as well. On the face of it, it should always either get error or empty the buffer. But in reality it may depend on the details of implementation of libgpsd and changes in the API. If you prefer I will implement a timeout mechanism with a message to contact developers if it ever happens. What do you think?

**Comment by knro** [comment]
Yeah I think that's a good idea, it doesn't hurt.

**Comment by jochym** [comment]
Fingers crossed ;)

**Pull request merged**
