### PR TITLE
SVBONY: Fixed some bugs and added workaround code for SVBONY Camera SDK

### PR DESCRIPTION
**Pull request by jctk**
Fixed some bugs and added workaround code for SVBONY Camera SDK
- Save default value to prevent crash(Merge with d1622b9)
- Changed the SDK to set the ROI only if it is different from the current ROI when setting the ROI.
- Added code to call SVBSetCameraMode function in SVBONYBase::Connect(). This is a workaround code for a bug in the SDK.
- Fixed parameter for setting target cooling temperature in SVB_TARGET_TEMPERATURE.
- Modified to set Bayer pattern to INDI control panel in SVBONYBase::Connect changes

SVBONY re-implementing monochrome camera
- Related modifications have been made but not yet tested with a monochrome camera (testing will be conducted after the actual equipment is obtained).

### CODE REVIEW

**Comment by jctk** [comment]
Hi Jasem
I want you to Resolve all Conflicts with my PR.

**Comment by knro** [comment]
I am currently traveling so won't be able to resolve any conflicts. Can you
please rebsse?

**Comment by jctk** [comment]
Okay. I'll try to rebase.

**Comment by jctk** [comment]
I've rebased this branch.

**Pull request merged**
