### PR TITLE
Interferometer

### PR DESCRIPTION
**Pull request by iliaplatone**
Fixes for bug #232

### CODE REVIEW

**Comment by xsnrg** [comment]
@iliaplatone I pulled your fork to give it a go, but I am still getting errors. I see @knro merged it, so will wait for the automated build and post results.

**Comment by xsnrg** [comment]
The library builds fine, and it did locally as well.
https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/build/1768001/

The driver fails in the same way it does for me locally:

https://download.copr.fedorainfracloud.org/results/xsnrg/indi-3rdparty-bleeding/fedora-33-x86_64/01768078-indi-ahp-correlator/builder-live.log.gz

**Comment by iliaplatone** [comment]
@xsnrg can you post the build log?

**Comment by xsnrg** [comment]
certainly. Are you not able to view the link?
```
In file included from /builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.cpp:28:
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h: In destructor 'virtual Interferometer::~Interferometer()':
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h:48:28: error: 'xc_get_nbaselines' was not declared in this scope; did you mean 'ahp_xc_get_nbaselines'?
   48 |         for(int x = 0; x < xc_get_nbaselines(); x++)
      |                            ^~~~~~~~~~~~~~~~~
      |                            ahp_xc_get_nbaselines
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h:51:28: error: 'xc_get_nlines' was not declared in this scope; did you mean 'ahp_xc_get_nlines'?
   51 |         for(int x = 0; x < xc_get_nlines(); x++)
      |                            ^~~~~~~~~~~~~
      |                            ahp_xc_get_nlines
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h:52:13: error: 'xc_set_power' was not declared in this scope
   52 |             xc_set_power(x, false, false);
      |             ^~~~~~~~~~~~
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h:54:9: error: 'xc_set_baudrate' was not declared in this scope; did you mean 'ahp_xc_set_baudrate'?
   54 |         xc_set_baudrate(R_57600, false);
      |         ^~~~~~~~~~~~~~~
      |         ahp_xc_set_baudrate
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.h:55:9: error: 'xc_disconnect' was not declared in this scope; did you mean 'tty_disconnect'?
   55 |         xc_disconnect();
      |         ^~~~~~~~~~~~~
      |         tty_disconnect
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.cpp: In member function 'void Interferometer::Callback()':
/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator/indi_ahp_correlator.cpp:65:126: error: 'ahp_xc_get_crosscorrelator_jittersize' was not declared in this scope
   65 |     unsigned long* crosscorrelations = static_cast<unsigned long*>(malloc(static_cast<unsigned int>(ahp_xc_get_nbaselines()*(ahp_xc_get_crosscorrelator_jittersize()*2-1))));
      |                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/indi_ahp_correlator.dir/build.make:85: CMakeFiles/indi_ahp_correlator.dir/indi_ahp_correlator.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator'
make[1]: Leaving directory '/builddir/build/BUILD/indi-ahp-correlator-1.8.7.git/indi-ahp-correlator'
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/indi_ahp_correlator.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.NdyW0v (%build)
    Bad exit status from /var/tmp/rpm-tmp.NdyW0v (%build)
```

**Pull request merged**
