### PR TITLE
Upgrade Atik SDK to 2023.07.14.1456.

### PR DESCRIPTION
**Pull request by TallFurryMan**

### CODE REVIEW

**Comment by TallFurryMan** [comment]
I did not pick the `master` branch from the right repository 😑

**Comment by knro** [comment]
Shall I close this and then you can resubmit again?

**Comment by TallFurryMan** [comment]
I'll fix this during lunchtime.

**Comment by knro** [comment]
@TallFurryMan Any update?

**Comment by TallFurryMan** [comment]
I have a question about 4ad082b1, what was done there to MacOS files? Is there a specific change I should do before pushing?

**Comment by knro** [comment]
no, I will take care of that after you push (basically run it on MacOS to fix some links)

**Comment by knro** [comment]
missing header?

**Comment by knro** [comment]
CMakelists.txt should probably install the new header.

**Comment by TallFurryMan** [comment]
Versions are missing, and there's a new header that I didn't take into account in cmakelists. Not going very fast here 😅

**Comment by TallFurryMan** [comment]
Good to go. I might be able to test this tonight, but it means updating quite a lot of elements in the obs and rebuilding some for i386 and some for x64.

**Pull request merged**
