### PR TITLE
Dev versions - indi_dsi - use gain/offset for DSI 1/2

### PR DESCRIPTION
**Pull request by astrogene1000**
[DsiDevice.cpp.gz](https://github.com/indilib/indi-3rdparty/files/6291802/DsiDevice.cpp.gz)

### CODE REVIEW

**Comment by knro** [comment]
Thank you for the fix. You need to rebase first as many files were included in this PR.

**Comment by astrogene1000** [comment]
Sorry Jasem, I do not know how to do a re-base!
Not sure how more than one file got included either

**Comment by knro** [comment]
@bgilsrud Can you please check if the proposed changes are OK? I ran a diff, and it came up as this:

```
diff --git a/indi-dsi/DsiDevice.cpp b/indi-dsi/DsiDevice.cpp
index ffc634e2..02220d43 100644
--- a/indi-dsi/DsiDevice.cpp
+++ b/indi-dsi/DsiDevice.cpp
@@ -726,9 +726,14 @@ int DSI::Device::startExposure(int howlong, int gain, int offs)
         {
             status = command(DeviceCommand::SET_VDD_MODE, VddMode::AUTO.value());
         }
-        status = command(DeviceCommand::SET_GAIN, 0);
+        if (log_commands)
+            std::cerr << "Gain  = " << gain << " Offset = " << offs << std::endl;
+
+        // status = command(DeviceCommand::SET_GAIN, 0);
+        status = command(DeviceCommand::SET_GAIN, gain);
         // status = command(DeviceCommand::GET_READOUT_MODE);
-        status = command(DeviceCommand::SET_OFFSET, 0x0ff);
+        //status = command(DeviceCommand::SET_OFFSET, 0x0ff);
+        status = command(DeviceCommand::SET_OFFSET, offs);
         status = command(DeviceCommand::SET_FLUSH_MODE, FlushMode::CONTINUOUS.value());
         status = command(DeviceCommand::GET_READOUT_MODE);
         status = command(DeviceCommand::GET_EXP_TIME);

```

**Comment by astrogene1000** [comment]
Hi Jasem,

The diff correctly shows the updates I added
A log out if logging commands enabled, two lines commented out old setting 0 and ff for gain/offset and 2 lines added to set the given gain and offset

**Comment by bgilsrud** [comment]
Looks good to me!

**Comment by knro** [comment]
Thanks, I merged the changed.

**Pull request closed without merging**
