### PR TITLE
move udev rules from /etc/udev/rules.d to /lib/udev/rules.d

### PR DESCRIPTION
**Pull request by alteholz**
Some time ago (with version 0.140-1 of the udev package) the handling of udev rules was changed. The default rules shall now live in /lib/udev/rules.d.

Most indi drivers already comply with this, except indi-dsi and indi-orion-ssg3 (those are updated with this PR).
Other indi driver just need an update of their documentation.

More information about this can be found in [1].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=586668

### CODE REVIEW

**Comment by knro** [comment]
Thanks!! @xsnrg Is this OK with you as well?

**Comment by xsnrg** [comment]
yes, this should be fine.

**Comment by knro** [comment]
@alteholz I take it we need a similar PR in INDI core as well?

**Comment by alteholz** [comment]
@knro oh, yes, if nobody beats me, I will have a look

**Comment by alteholz** [comment]
@knro INDI core already moved to /lib/udev ...

**Pull request merged**
