### PR TITLE
Clear Bayer flag when MonoBin is active

### PR DESCRIPTION
**Pull request by const86**

### CODE REVIEW

**Comment by knro** [comment]
Thanks, I don't think we need to query these values every time, we already have the latest values in the properties themselves. The code would be simplified and no unnecessary SDK calls are made.

**Comment by const86** [comment]
> Thanks, I don't think we need to query these values every time, we already have the latest values in the properties themselves. The code would be simplified and no unnecessary SDK calls are made.

Well, OK. I thought about it and chose the other way randomly :)
How are INDI and ASI states synchronized? I mean, if I start exposure with MonoBin enabled and then switch if off in the middle of exposure, I should still regard it as enabled somehow.

**Comment by knro** [comment]
Right, you can create a new member variable to keep track of monobin and only update it when capture is not in progress. The goal is reduce any unnecessary overhead by the extra calls to the SDK. If exposure is set to 0.001s then each call matters.

**Comment by knro** [comment]
I'll merge this for now and check the performance issues, it might not be a big issue after all.

**Pull request merged**
