### PR TITLE
Check - Remove manual symlinks - DO NOT MERGE

### PR DESCRIPTION
**Pull request by pawel-soja**
@knro Can you check if you still need DEB_DH_LINK_ARGS?
I started doing package tests on Ubuntu and everything looks fine.

### CODE REVIEW

**Comment by pawel-soja** [comment]
I built all the packages on Ubuntu and noticed a few collisions.
For example:
https://github.com/indilib/indi-3rdparty/blob/48f9e13473e1d14c962bf530a0350548b5832041/debian/libahp-xc/control#L8-L22

The `libahp-xc` and `libahp-xc-dbg` packages have the same content and cannot be installed together.

Back to the topic, I believe DEB_DH_LINK_ARGS was needed before https://github.com/indilib/indi-3rdparty/pull/384 or earlier changes.

**Comment by knro** [comment]
It would be great if we can remove the manual symlinks, it's a chore to update them every time there is a new release.

@iliaplatone Can you please check the issue above with libahp-xc?

**Comment by pawel-soja** [comment]
@knro @iliaplatone I prepared a PR to merge (#392) if everything is correct.

**Comment by knro** [comment]
I will test this today on Launchpad to see if it produces a valid deb file as I had to add specific hacks before just to make it work on Launchpad build farm.

**Pull request closed without merging**
