### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by pawel-soja**
Hi!

Updated POLLMS and defineProperty.
By the way, I corrected some of the warnings tiring during compilation.

### CODE REVIEW

**Comment by knro** [comment]
Great thanks, it's SO MUCH CLEANER now! I probably need to update some of the documentation now :D

**Comment by lboclboc** [comment]
Hi, this pr broke the build of indi-rpicamera, the getCurrentPollingPeriod is missing. Do I need to include some more files or what should I do?

**Comment by pawel-soja** [comment]
Hi @lboclboc 

you are probably using the old version of INDI Core Library.
Please rebuild the [master](https://github.com/indilib/indi) branch from source.
The changes are described in PR https://github.com/indilib/indi/pull/1327

**Comment by lboclboc** [comment]
Yes I realized this, thanks.

**Pull request merged**
