### PR TITLE
Touptek step 3

### PR DESCRIPTION
**Pull request by touptek**

### CODE REVIEW

**Comment by knro** [comment]
Great job! However, I don't think  8da2c5b is OK. You should let INDI control this as per the user. This feature is disabled by default. If the user enables it, then the driver should just cool to the temperature as sent by the INDI::Camera class as is. This is how all other drivers behave.

**Comment by touptek** [comment]
> Great job! However, I don't think [8da2c5b](https://github.com/indilib/indi-3rdparty/commit/8da2c5b59a5d6d4dd17e3929c296282bd4618fab) is OK. You should let INDI control this as per the user. This feature is disabled by default. If the user enables it, then the driver should just cool to the temperature as sent by the INDI::Camera class as is. This is how all other drivers behave.

ok. I'll revert it

**Comment by touptek** [comment]
On a x64 computer, stream more than 5 hours continuously using RGB format, there is no crash.
Can you have a try? @knro

**Comment by touptek** [comment]
Have another about 3 hours test, still ok. @knro

**Comment by knro** [comment]
Thanks, I will check this soon!

**Pull request merged**
