### PR TITLE
Add libmeadecam

### PR DESCRIPTION
**Pull request by bgilsrud**

### CODE REVIEW

**Comment by knro** [comment]
Thank you @bgilsrud ! Many users are looking forward to this. Do you have the list of exact models supported by this so we can add it to documentation?

**Comment by bgilsrud** [comment]
> Thank you @bgilsrud ! Many users are looking forward to this. Do you have the list of exact models supported by this so we can add it to documentation?

This adds support for:
* Meade DSI IV Mono and Color
* Meade LPI-GM and LPI-GC
* Meade LPI-GM Advanced and LPI-GC Advanced

I think these are all of the cameras that Meade has sold in the past few years.

**Comment by bgilsrud** [comment]
I tested that this works on both an LPI-GM and LPI-GM Advanced cameras.

**Comment by knro** [comment]
Thank you so much!

**Comment by knro** [comment]
I am getting build error on x86_64, any ideas? I can build packages fine for arm64

```
/usr/bin/cmake -E cmake_link_script CMakeFiles/meadecam.dir/link.txt --verbose=1
/usr/lib/ccache/cc -fPIC -g -O2 -ffile-prefix-map=/home/jasem/Packages/libmeadecam-package-x86_64-stable/libmeadecam=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -Wa,--noexecstack  -Wall -Wextra -Wno-unused-but-set-variable -Wno-format-truncation -g -O3 -DNDEBUG -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro  -Wl,-z,nodump -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -pie  -shared -Wl,-soname,libmeadecam.so.1 -o libmeadecam.so.1.0 CMakeFiles/meadecam.dir/meadecam.c.o  -lusb-1.0 
/usr/bin/ld: /tmp/ccOljiHk.ltrans0.ltrans.o: warning: relocation against `Meade_Toupcam_get_FpgaVersion' in read-only section `.text.startup'
/usr/bin/ld: /tmp/ccOljiHk.ltrans0.ltrans.o: relocation R_X86_64_PC32 against symbol `Meade_Toupcam_Version' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by naheedsa** [comment]
@bgilsrud , Can you please attach INDI driver tabs screenshots and more information in a zip . So, we can include it.

**Pull request merged**
