### PR TITLE
WIP: Generic Celestron AUX telescope driver

### PR DESCRIPTION
**Pull request by jochym**
Moved and merged code from nexstarevo driver.
Compiles and links. Probably does not run at all yet.
Starting point for restructuring required for having 
all communication channels enabled in the driver.
The name change comes from the fact that,
it is no longer NexStar Evolution driver but aims to be a generic 
Celestron AUX protocol driver the way EQmod is a skywatcher protocol driver.

### CODE REVIEW

**Comment by jochym** [comment]
@fabriziop I have created this PR to facilitate the restructuring work.
I think that it will be better to fix the driver for real instead of ptching it into working by multiple hacks and redirections. Please check this. I'll post more code soon as I fix regressions from the NSE driver.

**Comment by jochym** [comment]
@knro I added you to the PR just to let you know what we are doing.
The code is not ready for review so do not waste your time on details.
I will ping you again when I fix all regressions from the legacy NSE driver.

**Comment by jochym** [comment]
I tested the network comm. At the basic level it works. More testing is needed.

**Comment by fabriziop** [comment]
Ok, I am looking at it.

**Comment by jochym** [comment]
For me it is not tracking properly over net but that is probebly due to the RTS/CTS and other communication setup problems. There are some timeouts etc. But this is all fixable.
I think this is a good starting point. I would imagine you can work on fixing any regressions with serial over PC-port at first (I have no access to such setup) and I will concentrate on network regressions. And then we can work on HC/serial together. You can make a PR against my working branch (celestronAUX) and I can merge them into this PR if there are no network regressions. Or you can work on this PR directly (I think).

**Comment by fabriziop** [comment]
@jochym: I have tested it with my current setup, PC port serial: all communication seems to work without changes. So, on the serial side is ok for me, at this step.

About next driver developement, here are some ideas.

The driver methods/functions are already, but may be improved, on three levels.
1. Scope functionality: goto, sync, etc.
An improvement may be to try to have only one function (scope_cmd) to interact with lower level.
2. Scope commands: assemble required commands.
Probably at this interface level, more than one function (send_scope_cmd), will be required to interact with the communication level. 
3. Scope communication: send command and return response, manage comm. channels HC, PC, Net. Next development step for me.

Obviously, use libraries as much as possible. I have seen inside tty_read/write some code specific for some drivers. Perhaps, the RTS/CTS control flow can be embedded into these functions, I don't know if this follows the indilib strategy.

**Comment by jochym** [comment]
@fabriziop  It is good to know that there are no substantial regressions with your side. 
Unfortunately network comm is terribly slow on this one - this may be due to the specifics of the Wi-Fi interface in the scope. Your ideas for consolidation and integration are interesting and I will consider them on the clean-up phase. Now I need to make the network working again. I will be posting some changes to this PR today - in order to insulate the paths between network and PC-port serial comm for the development time. Please test/correct them for regressions in your part. I will appreciate your help here since I have no way of testing it myself.
Also, do you have equatorial setup or AltAz?

**Comment by jochym** [comment]
@fabriziop I just pushed some changes - mostly clean-up and debugging instrumentation.
This should not change anything in your case. I would really appreciate if you could verify this.
I will base my further work on this stage. If you confirm, I will make the net path separate and make it work - to be merged when we identify why it got so unresponsive after the change.

**Comment by fabriziop** [comment]
My setup is equatorial, currently my scope is off site for maintenance and software testing. So, I can test communication well, but poorly pointing and tracking. Now, I am using  CCD simulator.

Ok, I'll test your last commit today.

**Comment by jochym** [comment]
Great. The equatorial mode also needs testing. My setup is AltAz.
The tracking and pointing should be common for both cases. 
I expect any errors to be of rather obvious nature (e.g. pointing to zenith instead of Polaris).

**Comment by jochym** [comment]
@fabriziop The second push actually works as before. I have replaced the rw/_tty procedures with network routines incase of TCP connection. The problem is the querry-response by packet style of communication. For unknown to me reason this leads to pile-up of messages which the driver cannot consume fast enough. This leads to extreme lag in communication. Switching to reading with network procedures fixed the whole problem. Are there any problems with lag in your setup?

**Comment by fabriziop** [comment]
@jochym: No, I have not experienced any lag with the serial connection.

**Comment by jochym** [comment]
@fabriziop one more thing to test: gps emulation. If you have gpsfix and gps driver connected to the mount driver - when the driver is connected to the scope it should emulate celestron gps for the hand controller. Just connect the HC and check if the GPS works (unless you have internal GPS that is).

**Comment by fabriziop** [comment]
@jochym I am not sure to have properly synchronized my repo with your last commits. Since I am not so easy with github branching mechanics, please tell me how to do it. Thanks.

**Comment by fabriziop** [comment]
@jochym may be I have found it, git checkout celestronAUX :)

Also last comits have no impact on my setup that still works well.

**Comment by jochym** [comment]
@fabriziop glad to hear. I may need to make the emulator optional (add a switch) if it disturbs the working of internal GPS, so pay extra attention to that. We may be geting closer to final shape of this driver. One last step will be making serial-over-HC work.

**Comment by fabriziop** [comment]
@jochym I am studying passthrough commands as coded in celestrondriver.cpp. They have a relatively different structure. 8 bytes fixed length, byte n.1 is parameter len + 1, byte n.2 destination, byte n.3 command id, bytes n.4-5-6 room for command parameter, if any. Finally byte n.7 response len. No source id, no checksum, no variable length. Perhaps, the better way is to split command assembling in the same way you have split readMsgs for serial and network. In the next few days I willl work on it.

**Comment by fabriziop** [comment]
@jochym I added the HC serial protocol to the driver. It compiles and links. Now I am going to debug, a lot of bugs to squash, I think.

**Comment by jochym** [comment]
I spend some time last two days testing the present code. It seems to work fine. I was able to run some multi-frame photo sessions with fairly nice results (for AltAz mount at least). I think it works the same as the old driver. I would still prefer to have it working over common comm library but this is not so bad (we have it contained nicely). There seems to be a slight instability connected with allocations - sometimes the driver dies with bad alloc. 
So here is the todo list from my point of view:
1. Make sure the serial path works the same as network path
2. I think we need to move to simpler (C) data types and avoid any allocations. 
3. Implement cordwrap control interface (It is already in the motor controller firmware), 
4. Implement adiustable park position (probably for both axis for the EQ case)
5. Enable network scanning for the scope (it is implemented - just deactivated).
5. Implement HC serial bridge. This might be pushed after merge of current stage

**Comment by jochym** [comment]
Great @fabriziop ! Put your work in the separate branch in your fork of indi-3rdparty on github. That will make it possible for me to test it as well.

**Comment by fabriziop** [comment]
@jochym I have just pushed my changes to fabriziop/indi-3rdparty, there is a branch hc-serial with the implementation of the hc serial pass through protocol.
To keep changes to a minimum, I put a converter from AUX packet to passthrough packet before the sending function calls. In the same way, I put an AUX packet builder after the receiving function calls. The AUX packet is built using both the pass through response and both the original AUX packet that was converted to pass through before sending.
I have done a first rough debug, now the AUX protocol is still working on the PC serial port. In the next few days, I'll debug the pass through connection.

About your points, I agree. For command packet (binary) can be used a static buffer of unsigned char or more concisely uint8_t .

**Comment by fabriziop** [comment]
@jochym I finished the second round of debugging with several fixes. Now the driver connects correctly through the HC and it can control the scope. It works with HC version 4 (firmware 4.22) and with HC version 5 (firmware 5.31.9200). The HC port works @9600 baud and the AUX/PC port works @19200 baud, since booth are autodetected, I added an autospeed capability.
Now my scope is indoor, so I didn't look at GPS.
I pushed the last commit to fabriziop/indi-3rdparty, but I made some error and all my commits (n.3) for the HC serial link are in the celestronAUX branch and not in the hc-serial branch. I hope this is not a problem.

**Comment by jochym** [comment]
Great @fabriziop ! I will try to work on this next week. Right now I am busy organizing remote work wor our group in the institute. I hope you are safe in this hard times. Stay safe! I'll get back to you when I compile your branch.

**Comment by fabriziop** [comment]
@jochym  Good! Remote work is essential to be safe. Here, from several weeks, I am locked down at home with computer and scope, waiting for this long night to pass.

**Comment by knro** [comment]
Great work @fabriziop & @jochym. is this ready to land?

**Comment by jochym** [comment]
Give me few more days, please @knro and @fabriziop . I need to finish something first to have one day for testing this.

**Comment by jochym** [comment]
@fabriziop : are you sure the HC conection works for you? After building this PR I have got no comm with HC (it works with CelestronGPS driver). The log looks like this:
```
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: pid=20269 rfd=3 wfd=8 efd=9
2020-04-28T06:12:14: listening to port 7624 on fd 6
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: Celestron AUX instancing
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: 
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: snooping on GPS Simulator.GEOGRAPHIC_COORD
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: snooping on GPS Simulator.TIME_UTC
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: snooping on Dome Simulator.DOME_PARK
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: snooping on Dome Simulator.DOME_SHUTTER
2020-04-28T06:12:14: Driver ./indi_celestronaux_telescope: EnumeratePlugins - found plugin SVD Math Plugin
2020-04-28T06:12:55: Client 0: new arrival from 127.0.0.1:35960 - welcome!
2020-04-28T06:12:55: Client 7: new arrival from 127.0.0.1:35962 - welcome!
2020-04-28T06:13:33: Driver ./indi_celestronaux_telescope: CAUX: connect 3
2020-04-28T06:13:33: Driver ./indi_celestronaux_telescope: detectRTSCTS = false.
2020-04-28T06:13:34: Driver ./indi_celestronaux_telescope: Send: (fe) 20 -> 11: 
2020-04-28T06:13:34: Driver ./indi_celestronaux_telescope: Send packet: <50 01 11 FE 00 00 00 02>
```
What kind of serial connection are you using?

**Comment by jochym** [comment]
@fabriziop if possible, check if serial on aux/hc still works for you. I have merged and cleaned up the connection code. For me it works for both network and serial-over-HC connection. My scope does not have PC-port so please check that in particular. I am getting ready to release this.

**Comment by fabriziop** [comment]
@jochym I checked serial connection with both HC and PC ports and everything works as before.

**Comment by jochym** [comment]
I think we can consider merging. I have added a skeleton for the support of cordwrap control.
It is just an UI without actual control. My tests are also fine. I have removed network autodetection as well. It hangs on start-up. This needs to be a push-button action.

**Comment by fabriziop** [comment]
@jochym  We have done a lot of work and completed all possible communication channels available on Celestron scopes. No other driver have such a wide communication options. So, I agree for merging at this point, also in the hope to have some feedback, even if I think that for a fully operational driver 3 more features have be added. The cordwrap control whose foundation you already laid. The option to choose among emulated GPS and scope real GPS (this is my case). The option to choose among AZM/ALT or equatorial mount (this is my case). We can leave this job for the next development round. I can work on it in the next weeks/months.

**Comment by knro** [comment]
Congratulations @jochym & @fabriziop on such an amazing work. I think what is left now is to have proper & detailed driver documentation for end users. The [existing documentation](https://indilib.org/devices/mounts/celestron/celestron-nexstar-evolution.html) is quite preliminary and not up to INDI standards.

It would be great if a documentation similar to [EQMod](https://indilib.org/devices/mounts/eqmod.html) can be written for this driver so that it becomes accessible to user. It should include any limitations, warnings, or info cards of interest.

**Comment by jochym** [comment]
@knro I agree about documentation. But do you think it is a show-stopper before merging?
Should I decide when to merge? I will start the docs right away, I'll try to make it better. Also, I think that we will be phasing out the nexstarevo driver - preferably at next point release. This one has all the features of NSE, making it redundant and confusing. I have one question to you Jasem: in the course of this development I have spotted a difficulty/problem with tty_read function over a network connection. I was unable to use it for the driver since it was terribly slow and lagging (much slower than over actual 9600 serial connection). The tty_write works fine - so we ended up with mixed reading procedures and integrated write procedures. I would rather have it more integrated. If you could look at this issue at some moment I would appreciate it.
And another, rather embarrassing question: Is there any place/example I can use for building the driver interface properly (i.e. switches, buttons etc)? At the moment I am hunting in other drivers for examples at this is suboptimal. Am I missing something?
@fabriziop it would be impossible without your excellent contribution. I hope to cooperate with you on the driver in the future. There is a number of features to implement still. I'll implement GPS emulation switch today. Other features should be present as well (firmware versions, voltages, mount lights control, max speed control, axis limits, etc.), so there is a ton of work before 1.0 ;).

**Comment by knro** [comment]
@jochym The docs are not a show-stopper, you can proceed with the merge. For the tty_read, did you end up using one optimized for TCP/IP? If yes, where? For the last question on driver interface, I don't completely understand. Like a template driver?

**Comment by jochym** [comment]
@knro Ok. I am starting the docs anyway ;). 
1. We have used two functions serial_readMsgs (that one uses wrapped stock tty_read) and tcp_readMsgs for the network read (and that one uses standard network stack functions). For writing we use wrapped (hardware flow control is required over PC/AUX port) tty_write and it works fine. This is not a huge problem. I am just wondering why it is actually much slower for network communication. It may indicate that we are hitting some corner case or using the functions incorrectly. Your input will be appreciated. Still this issue is not stopping anything.
2. Regarding the example. No, not the driver, you have nice examples in the docs of drivers (in fact the whole NSEvo/CAUX is just adapted and reworked example). I mean actual user interface elements for the drivers. Things like: here is how to make a push button, new tab, text field, number entry field, switch etc. As usual with UI coding it is a little convoluted and there is certain amount of required boiler-plate code. I think that example "gallery" of available interface elements and empy hooks for controlling the driver added to one of the examples in the tutorials will be very useful for the beginning developers. Or maybe I am just missing something which is already there? It is just a suggestion.

**Comment by knro** [comment]
Well INDI is just an XML communication protocol. So basically any client can use whatever GUI to represent the properties. I suppose I can write general guidelines for GUI applications on how to represent the properties.

+ Push button: SWITCH property with ISR_1OFMANY or ISR_ATMOST1 rule.
+ Dropdown menu: SWITCH ISR_1OFMANY with n > 4
+ Check Box: SWITCH property with ISR_NOFMANY rule.
+ Text: TEXT property.
+ Number Spin Box: NUMBER property with min < max and step > 1
+ Slider: Number property with max-min / step <= 50 (or whatever value the GUI wants to use).
+ LED: LIGHT property

**Comment by jochym** [comment]
@knro Obviously, I am not making myself clear. I mean the driver control elements represented by the client in the indi panel window. The properties you enumerated. There is certain amount of code you need to understand and write in multiple methods of the driver object to have a complete and functioning user interface produced by the client. I think it is not described in a single place - just scattered around all the indi docs. E.g. right now I need to add a bunch of properties to the driver for a number of features of the mount: cordwrap, goto approach and size, battery status, etc. Each one needs a different type of UI element. Right now I will simply look trough several drivers and just copy the snippets - hoping I did not miss anything. I would rather have a single example driver with all elements properly implemented, and be sure I am doing things the right way. 
You may wonder why this is needed, but by virtue of doing indi for a long time you may not realize that it is quite a complicated system and fairly intimidating for a novice developer. 
Understand, please, I am not requesting anything - I will manage the way I did to this point. I just spotted a weak point in the docs, which may not be so obvious to a seasoned indi developer as yourself, and just letting you know about it.

**Comment by jochym** [comment]
@knro on a separate issue. The C-AUX driver seems to have a slight long-time instability. Sometimes it just crashes and gets restarted by the indiserver. What is your best way to debug a driver? Attach a debugger to the running process? That is the way I intend to go about it, but maybe you have a better way. Any advice will be appreciated.

**Comment by knro** [comment]
Hi Pawel, Ok I will add one sample driver that demonstrates all the properties. However, you need to think in terms of properties and not GUI per se. You cannot guarantee that all INDI GUI clients are implemented in the same way. So what might appear in one GUI client is not necessary guaranteed to be in another.

For debugging, use gdb like this

gdb -ex "set follow-fork-mode child" -ex run --args indiserver -v ./indi_foo_bar

**Comment by jochym** [comment]
@knro Thanks for the debugger hint. I understand these are properties and client is free to present them (or not) any way it wishes. That was just a mental shortcut.

**Comment by jochym** [comment]
@fabriziop : I have implemented simple version of missing basic features: cord wrap, GPS emulator switches and networked scope detection. I also ran a 12h continuous tracking run and 32 alignment points run without any issues. I also updated the network scope simulator. I would appreciate if you would run another round of testing with your scope, and then we can finally merge.

**Comment by fabriziop** [comment]
@jochym OK

**Comment by fabriziop** [comment]
@jochym I tested again with both serial connections (HC & PC) and all motion control is good for me. SInce my scope is indoor now, I am not able to do real astronomical tests.
A couple of things.
1. a double click on the off button is needed set the cord wrap status from ready to idle.
2. the GPS switch do not appear in the "Mount info" tab, am I missing to load some driver? Now, my configuration has CCD simulator and celestron AUX only.

**Comment by jochym** [comment]
I'll check both @fabriziop , You need gpsd or gps simulator driver for gps emulation to work, but the switch should be there anyway. Actually, I think we can add gps functionality to the driver for scopes like yours. Unfortunately I would be unable to test it with my setup (I have no GPS in the scope). But AUX commands support all required GPS functions to have it function as a gps driver if the scope has the gps.
I think you need to have

**Comment by knro** [comment]
@jochym This PR is not yet ready for merging? What's pending?

**Comment by knro** [comment]
I'll merge this for now to get more user testing and exposure. Thank you all for the wonderful work!

**Comment by jochym** [comment]
Great. I was waiting for some good weather to run some more tests but since i did not spot any functional problems so far I think this is a good decission. Thanks. I am looking forward to some feedbeck as well.

**Comment by knro** [comment]
@jochym @fabriziop Can we get some documentation started for this drivers? I'm beginning to receive questions on it and realized we have no documentation in INDI. We have a documentation template for mounts.

**Comment by fabriziop** [comment]
@knro I'll be glad to contribute for my part. Please, point me to the doc template.

**Comment by knro** [comment]
@fabriziop Great! Please check out the [templates](https://github.com/indilib/indi/tree/master/drivers) and also [EQMod documentation](https://indilib.org/devices/mounts/eqmod.html) for what to expect.

**Comment by jochym** [comment]
I'll try to do my part as well. The updated build docs and short intro are there. @knro would you add this to the nightlies at lounchpad? I would argue replacing nexstarevo. There will be really no point in keeping NSE in the next release. There is no functionality which was not ported to CAUX.

**Comment by fabriziop** [comment]
I have written some doc about serial connectivity. I am not sure where to put it, so it is appended below. Feel free to correct, to modify and to suggest. 

----

## Connectivity

### USB/Serial

Celestron AUX driver can use any type of serial connection between the three
offered by Celestron scopes (i.e. CPC series). The serial connections are
listed below with their main characteristics.

1. **HC**: serial cable connected to hand controller serial port.
  - 4 pins connector (RJ11).
  - 3 wires used: GND, TX, RX.
  - RS-232 serial voltage levels (+5V,-5V).
  - 9600 baud transmission speed.
  - No transmission flow handshake, no echo.
  - Command protocol: pass through.

2. **AUX**: serial cable connected to Celestron AUX port.
  - 6 pins connector (RJ12).
  - 5 wires used: GND, TX, RX, CTS, RTS.
  - TTL serial voltage levels (+5V, 0V).
  - 19200 baud transmission speed.
  - Half duplex CTS/RTS handshake with echo.
  - Command protocol: [AUX](https://paquettefamily.ca/nexstar/NexStar_AUX_Commands_10.pdf).

3. **PC**: serial cable connected to Celestron PC port.
  - 8 pins connector (RJ45).
  - 5 wires used: GND, TX, RX, CTS, RTS.
  - RS-232 serial voltage levels (+5V,-5V).
  - 19200 baud transmission speed.
  - Half duplex CTS/RTS handshake with echo.
  - Command protocol: [AUX](https://paquettefamily.ca/nexstar/NexStar_AUX_Commands_10.pdf).

Celestron AUX driver autodetects the type of serial connection, setting 
proper transmission speed, proper serial line handshake and proper command
protocol.

Serial connections details are just shown as an aid for Celestron scope to
computer cabling.

As modern computers generally no longer have serial interfaces, a convenient way
to make a serial connection to a Celestron scope is to use an USB to serial
converter with the proper cable as mentioned in the previous list.

Beware of cheapest USB/serial converters, they have serial lines with
TTL levels (+5V,0V). So, they works with AUX port only. Connections to HC and
PC ports require a true USB/RS-232 serial converter with symmetric voltage
levels (+5V,-5V).

### First time connection

INDI Celestron AUX connection tab.

To select serial connection simply press "Serial" button of "Connection Mode"
property in **Connection** tab and set the USB port where Celestron scope is
connected to.

Baud rate is set automatically by driver. Displayed baud rate may differ from
real interface speed.

#### Linux USB

If the controlling system, i.e. a raspberry pi, runs a linux operating system,
when more than one USB device are connected, the persistence of USB port number
for the same physical USB port is not guaranteed after a system reboot.
  
This problem has two solutions:

1. Enable USB port scan in communication tab page.

2. Bind USB device under a static name.

Usage of USB port scan is straightforward, you just need to enable it in the
Celestron AUX **Connection** tab. Sometimes, if you have several devices
connected to USB, USB scan can fail or can mess up your devices.

The alternative solution of USB static name always works, but it is a little
more tricky to set up. Several examples can be found searching over internet for
"how to bind USB device under a static name".


----

**Comment by knro** [comment]
@jochym done, it's in nightly ppa
@fabriziop Great, you can post it here and then later I can add it to website. Which celestron telescopes are *exactly* supported. We need to put all the models. Another question that pops up is whether a handset is required for initial calibration or not, I presume not with this driver at all, but it's best to clarify explicitly.

**Comment by jochym** [comment]
I have moved the above nice description to indi site. Editing it a bit (https://www.indilib.org/devices/mounts/celestron/celestron-aux-driver.html). Please @fabriziop check it there and maybe edit it further there.

**Comment by fabriziop** [comment]
@jochym Great! I have seen some minor format typos, but to correct them there, some access is needed, I think.

**Comment by fabriziop** [comment]
@knro About a list of telescope models supported by driver.
Jochym and I developed and tested the driver for our telescopes (Nexstar Evolution and CPC) with control ports:  serial SkyFi, HC, AUX and PC. Currently, this is the tested working list. Meanwhile this list grows rapidly, I hope, by user contribution, instead of a list of working models, I suggest to show some  rules allowing to say if a given Celestron model is probably expected to work or not with Celestron AUX driver. Jochym has already written about this into "Features" section. Perhaps, it can be extended a little.
An example, I have tested 2 HCs, one with fw NXS 4.22 and one with fw NXS 5.3 .  So, I can say that any Celestron model that can be controlled by one of these HCs probably works with Celestron AUX driver. But this rule has its own complications. Both my HCs have a square jack (RJ11) serial port. Most recent HCs have a mini USB port, the external USB to serial converter is no more needed, since it is embedded into HC. Pushing beyond my inference, can I say that also this kind of HC is probably expected to work? To be more conservative or to be more daring? 

The connection to the handset is used in a completely transparent mode. Any alignment is made by the driver without no need of the handset: EQMod style.

**Comment by jochym** [comment]
The HC acts only as a mentioned level converter/serial protocol translator. As for the USB HC - they have their own usb-serial converter inside so should work exactly the same as the serial over usb connection. But until we test more physical scopes (esp. german mounts) we cannot say they are supported - only that they are "probably supported" or "expected to work". I understand @fabriziop has his CPC on equatorial wedge. So we have both modes Alt/Az and EQ tested.

**Comment by knro** [comment]
I think we need to list the models for now , plus how to connect to them exactly. Also, how is alignment performed? Alt-Az vs EQ. North vs southern hemisphere considerations? We need screenshot for each tab in the driver + documentation on it.

**Comment by jochym** [comment]
OK @knro we will try to make it ASAP. @fabriziop could you describe EQ alignment procedure?
I have no access to EQ mount here.

**Comment by fabriziop** [comment]
@jochym Ok, I'll do an effort to move my scope, currently indoor, to do EQ alignment and to describe it.
The celestron aux page have some typos. Please, make the following changes.
1. line: 4 pin connector (RJ11).
            ^ missing.
2. in connection list, where there is "AUX" and the following explicit URL, substitute in html file "AUX" and URL with
<a style="background-color: inherit; font-family: inherit; font-size: 1rem;" href="https://paquettefamily.ca/nexstar/NexStar_AUX_Commands_10.pdf">AUX</a>
3. in "First time connection" section, change **Connection** with <strong>Connection</strong>

**Comment by knro** [comment]
@fabriziop If you have indilib.org account, I can grant you privilege to edit directory. Send me your username there.

**Comment by fabriziop** [comment]
@knro my indilib username is Fabrizio. Thanks.

**Comment by knro** [comment]
@fabriziop thank you, you can now edit that page.

**Comment by jochym** [comment]
Thanks @fabriziop for corrections!

**Pull request merged**
