### PR TITLE
Remove all 'IS' Functions.

### PR DESCRIPTION
**Pull request by pawel-soja**
The 'IS' functions are unnecessary (https://github.com/indilib/indi/pull/1375) and their different implementation may damage the driver.

### CODE REVIEW

**Comment by knro** [comment]
Tested locally and remotely on observatory, and everything looks good now! Great job! I think we need to document the use of the loader class for future drivers as prospective developers are probably not aware of this.

@TallFurryMan @xsnrg Can you please check as well?

**Comment by xsnrg** [comment]
https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/build/2153075/
Running indi-asi against this latest commit now in Copr

**Comment by xsnrg** [comment]
Looks good here.

**Comment by escribana** [comment]
Looks very good here too! Checked my drivers and they are working again! (Thank you Pawel!) I'm looking forward for more documentation about the new loader.

**Comment by rkaczorek** [comment]
Well done! I will be testing this on my drivers over the weekend

**Comment by ken-self** [comment]
indi-asi-power and indi-rpi-gpio drivers used to use static variable "device" to reference a method from a static callback but this is no longer accessible.
`/home/ken/Projects/indi-3rdparty/indi-asi-power/asipower.cpp:39:5: error: ‘device’ was not declared in this scope`
 I tried loader.device but get:
`/home/ken/Projects/indi-3rdparty/indi-asi-power/asipower.cpp:39:12: error: ‘std::unique_ptr<IndiAsiPower> Loader::device’ is private within this context
   39 |     loader.device->DslrTimer(pi, user_gpio, level, tick);
      |            ^~~~~~
/home/ken/Projects/indi-3rdparty/indi-asi-power/asipower.cpp:29:35: note: declared private here
   29 |     std::unique_ptr<IndiAsiPower> device;`

How should I reference a method in my driver class from a static procedure?

**Comment by ken-self** [comment]
OK. I just declared device as public. Assuming there is no problem with doing that.

**Pull request merged**
