### PR TITLE
added usis driver

### PR DESCRIPTION
**Pull request by eco747**

### CODE REVIEW

**Comment by knro** [comment]
Thank you! What is this driver for exactly? Spectrograph?

**Comment by eco747** [comment]
Yes, this is a new driver.
This driver allow all Usis devices to be mounted on Indi.

You will find more informations here:
https://github.com/Shelyak-Instruments/USIS-Protocol

**Comment by knro** [comment]
Thanks. Please send the required Debian files as well. You can use debian/indi-shelyak as example.

Is there a documentation for using this driver?

**Comment by knro** [comment]
@eco747 Is there an update to this PR?

**Comment by knro** [comment]
Since this driver does not have any external dependencies, please submit it to INDI core driver instead of a separate 3rd party driver.

**Comment by eco747** [comment]
Hi,
It seems that the build failure is not in our driver but in indi-beefocus driver test.

I will follow your recommendation -> indi core driver.
Thanks

**Comment by knro** [comment]
Thanks! Will close this PR here. Please open a corresponding PR in INDI core repo.

**Comment by eco747** [comment]
Finally I need to reopen this PR because we will add dependencies soon.
Can you advise on how to correcct the indi-beefocus problem that is not our fault ?

**Comment by knro** [comment]
@eco747 What dependencies? You can safely ignore other drivers issues in CI.

**Comment by eco747** [comment]
Mmm thanks for the response.
In the core, there is no Spectrograph, can we add one or may I use an already existing category ?

**Comment by eco747** [comment]
nice, thx

**Comment by eco747** [comment]
I follow the tutorial to make my own driver in indi-core.

I just (and only) fork the core. Then git send me some emails with build errors:

example:

[ 91%] Building CXX object CMakeFiles/indi_uranus_weather.dir/drivers/weather/uranusmeteo.cpp.o
[ 91%] Building CXX object CMakeFiles/indi_vantage_weather.dir/drivers/weather/vantage.cpp.o
/Users/runner/work/indi/indi/indi/drivers/weather/uranusmeteo.cpp:526:41: error: unused parameter 'raw_time' [-Werror,-Wunused-parameter]
bool UranusMeteo::setSystemTime(time_t &raw_time)
                                        ^
[ 91%] Linking CXX executable indi_vantage_weather
[ 91%] Built target indi_vantage_weather
[ 91%] Building CXX object CMakeFiles/indi_openweathermap_weather.dir/indi_openweathermap_weather_autogen/mocs_compilation.cpp.o

I think there is an option in the compilation that says: treat warnings as errors, and the make do not pass.
Any idea ?

**Pull request closed without merging**
