### PR TITLE
AStarBox Plugin

### PR DESCRIPTION
**Pull request by mcgillca**
An indi plug in for AStarBox. This controls a HAT on a Raspberry Pi 5 that provides power for astro devices and a dew heater.

Find full details here: [AStarBox](https://www.astarbox.co.uk)

### CODE REVIEW

**Comment by knro** [comment]
Thank you! Do you have driver documentation with screenshots of each tab? We need to add it to INDI Documentation.

**Comment by knro** [comment]
A google or word doc would be great, thanks!

**Comment by mcgillca** [comment]
Dear Jasem,

As requested.

Please let me know if you need anything else.


Thank you again,

￼
￼

**Comment by knro** [comment]
Did you attach a file? it's not showing up on Github if you did.

**Comment by mcgillca** [comment]
[AStarBox Indi Driver.docx](https://github.com/user-attachments/files/16690332/AStarBox.Indi.Driver.docx)

HI - yes, I definitely included it in the email - but loaded it directly on GitHub instead.

Colin

**Comment by mcgillca** [comment]
I see that some checks failed, but they seem to fail on other drivers or libraries?

Also, this is only really needed for the Arch64 architectures - while the plugin should run on other devices, it won't have anything to connect to. Not sure if there is a way to flag that?

**Comment by knro** [comment]
@naheedsa Please coordinate with Joe to add the documentation

**Comment by mcgillca** [comment]
Thank you!ColinSent from my iPhoneOn 30 Aug 2024, at 09:30, Jasem Mutlaq ***@***.***> wrote:﻿
Merged #962 into master.

**Comment by knro** [comment]
@mcgillca There are some [issues in the driver](https://launchpadlibrarian.net/752217454/buildlog_ubuntu-noble-amd64.indi-astarbox_1.0+t202410011456~ubuntu24.04.1_BUILDING.txt.gz) that prevents creating packages for it. Can you please check them out? Right now the driver is not included in INDI v2.1.0 release due to these issues.

**Comment by mcgillca** [comment]
Thansk, Jasem.

Now fixed.

Colin

￼

**Pull request merged**
