### PR TITLE
[UNTESTED] Spectracyber base classes inheritage

### PR DESCRIPTION
**Pull request by iliaplatone**
Spectracyber inheritage of INDI::Receiver and INDI::Spectrograph

### CODE REVIEW

**Comment by knro** [comment]
@pawel-soja Is there a reason INDI 3rd party not building yet against INDI Master? is it because INDI master still fails? Btw, I talked with @TallFurryMan to look into the EQ500X test failures.

**Comment by pawel-soja** [comment]
@knro Yes, INDI Core needs to be fixed.

**Comment by knro** [comment]
It appears there are still some CI errors that needs to be fixed.

**Comment by iliaplatone** [comment]
Fixed the error. @knro can you check the code itself before merge?

**Comment by knro** [comment]
I believe this needs to be rebased.

**Pull request closed without merging**
