### PR TITLE
Work on SBony SV305M Pro camera support

### PR DESCRIPTION
**Pull request by thx8411**
Hi !

Some light refactoring on the cameras capabilities handling, in order to add the SV305M Pro support.
The SV305M Pro should work, but not tested yet (I don't own the device).

Best regards !

Thx8411

### CODE REVIEW

**Comment by knro** [comment]
Thanks. Can we work on the documentation? I need a jpg image of each tab in the driver. And perhaps some description on any special features. Anything to alert to user to? We really need to add proper driver documentation. You can zip the information and attach it here.

**Comment by thx8411** [comment]
Hello Jasem,

Sure, I will work on it. Should I use this kind of page as a template ? : 

https://www.indilib.org/ccds/player-one-astronomy-cameras.html

Best regards,

Blaise

**Comment by knro** [comment]
Sure that would work! Add as much detail as you believe necessary, including any quirks or warnings.

**Comment by knro** [comment]
I'll merge this for now, but please let me know whenever you have the documentation ready as it is very critical to have at this stage with increasing number of users for this driver.

**Pull request merged**
