### PR TITLE
Interferometer

### PR DESCRIPTION
**Pull request by iliaplatone**
@knro @ksnrg please check also my fork, build errors are not fixed yet on upstream

### CODE REVIEW

**Comment by xsnrg** [comment]
this time only 1 error locally:
```
indi-ahp-correlator/indi_ahp_correlator.cpp: In member function ‘void Interferometer::Callback()’:
indi-ahp-correlator/indi_ahp_correlator.cpp:65:126: error: ‘ahp_xc_get_crosscorrelator_jittersize’ was not declared in this scope
   65 |     unsigned long* crosscorrelations = static_cast<unsigned long*>(malloc(static_cast<unsigned int>(ahp_xc_get_nbaselines()*(ahp_xc_get_crosscorrelator_jittersize()*2-1))));
      |                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/indi_ahp_correlator.dir/build.make:82: CMakeFiles/indi_ahp_correlator.dir/indi_ahp_correlator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/indi_ahp_correlator.dir/all] Error 2
```

**Comment by iliaplatone** [comment]
Can you update the library? libahp_xc contains those definition from today

**Comment by xsnrg** [comment]
I am in your fork/branch, did another get pull just to make sure I was up to date. Built the library first, then am trying to build the indi-ahp-correlator from the same fork/branch, and getting the error.  Can you double-check to make sure you added and pushed all the changes up?

**Comment by iliaplatone** [comment]
Checkout the last commit.. you were right. I missed a change into the header file. Sorry.

**Comment by xsnrg** [comment]
No worries. It builds cleanly now.  Thanks!

**Pull request merged**
