### PR TITLE
indi-eqmod: Implement Snapport control 

### PR DESCRIPTION
**Pull request by geehalel**
This fixes the issue #39 and besides adds support for EQ6-R Pro mount.

- adds one or two snap port switches in the options tab depending on the mount model (hardcoded in HasSnapPort functions)
- adds EQ6-R Pro mount model with code 0x23 (with a built-in USB port)

### CODE REVIEW

**Comment by ACMACMACM** [comment]
> This fixes the issue #39 and besides adds support for EQ6-R Pro mount.
> 
> * adds one or two snap port switches in the options tab depending on the mount model (hardcoded in HasSnapPort functions)
> * adds EQ6-R Pro mount model with code 0x23 (with a built-in USB port)

Hi geehalel, 

I have an EQ6-R Pro mount and would very much like to use the Snap Port.  I can see the option in the Ekos>EQMount>Options menu and can turn it on, but after that, how can i control it?  There doesnt seem to be anywhere ive found to be able to then control it thereafter.

**Comment by geehalel** [comment]
Hi @ACMACMACM 
I'm not sure to understand what you mean by controlling the snap port. As is, the indi-eqmod driver toggles your snap ports when you use the switch in the Options tab. It is the role of a client to decide when to toggle the snap ports. If you want to use it for controlling the shutter release of a DSLR (I do for my old 350D), you may use a small script which will toggle the snap port when gphoto ccd starts an exposure. The code is [here](https://github.com/geehalel/indi/blob/eqsnap/3rdparty/indi-eqmod/eqsnap1.py). Use the file name in this script (<code>/tmp/eqsnapport1</code>) in the 'Shutter Release Port' option in gphoto CCD, and run the script from a terminal (exit with Ctrl-C).

**Comment by ACMACMACM** [comment]
Ok so Ekos would be the client in this case.  Id like to use the Capture module in Ekos to control the snap port of the camera.  Queue up a sequence of exposures in Ekos and instead of GphotoCCD controlling the camera via USB (which it cant do for my camera at this time) it would instead control the camera via the snap port solely.  No USB cable to the camera at all.  I didnt think this would work given Ekos needs to detect a camera in order to start, and to detect a camera it would have to be plugged in via USB (which im trying to avoid).

**Comment by ACMACMACM** [comment]
Thanks, that makes sense that the driver is doing it's part by toggling the snap port, and that a client would have to then control that toggling process. 

Can I ask what to do from here though as i'm not very technical.  Can i queue up exposures (eg. 20x60s exposures with an initial wait time of 5s, with a gap of 3s between each exposure) without the use of Ekos or GPhoto CCD, and only toggle the EQMod Mount snap port via terminal? What might that command line syntax look like?

**Pull request merged**
