### PR TITLE
Support for the V2 camera

### PR DESCRIPTION
**Pull request by lboclboc**
This patch will support the older V2 Raspberry PI camera

### CODE REVIEW

**Comment by knro** [comment]
Thank you! There is no version associated with this? what about debian changelog updates?

**Comment by HamHamFonFon** [comment]
Very interesting. I have a camera V2 NoIR and a problem : https://github.com/indilib/indi-3rdparty/issues/220. Is your fix will be patch my error ?

**Comment by lboclboc** [comment]
Ah, thanks. Ill look into that.
Regards, Lars

**Comment by lboclboc** [comment]
Thanks Jasem

**Pull request merged**
