### PR TITLE
Added Debian files for Pentax driver

### PR DESCRIPTION
**Pull request by karlrees**

### CODE REVIEW

**Comment by karlrees** [comment]
So I'm not sure why the pull request lists all of these other commits since they've already been pulled before.  Am I doing something wrong?

**Comment by knro** [comment]
It's alright, they're squashed anyway.

**Comment by karlrees** [comment]
Jasem- When/how does this get into the nightlies?  Just curious to test it out to see if everything gets installed correctly.

**Comment by knro** [comment]
Good question.. I haven't had time yet to work on this. Hopefully soon.

**Pull request merged**
