### PR TITLE
Weather Radio v 0.5

### PR DESCRIPTION
**Pull request by sterne-jaeger**
I've spent the last weeks with developing a refurbished version of the good old Arduino based weather driver and called it Weather Radio. Its still in a beta stage, but meanwhile ready for others to be tested. It contains:
- New Arduino driver that delivers sensor data as JSON document.
- New indi_weatherradio INDI driver that interacts with the Arduino driver and delivers weather info usable in the Observatory tab of KStars
main_control
- A completely rewritten HTML based UI for the weather  - see my local weather station http://weather.openfuture.de This UI uses an RRD storage for data history and a set of scripts to create JSON documents that are read from the browser to display the charts.

### CODE REVIEW

**Comment by knro** [comment]
Thank you, this is is really good. I'm now looking at this to add the radio weather observation for my observatory... how can I get started on this? any guide?

**Comment by sterne-jaeger** [comment]
Just very briefly, the real guide needs to be written.

1. Install the firmware: devices/Firmwares/weatherradio/weatherradio.ino
There is a config.h to configure the sensors
2. Install the INDI driver indi_weatherradio (as usual)
3. Copy add-on/weatherradio to /usr/local/share 
4. Configure the connection to your INDI driver in bin/wr_config.py
5. Integrate the html part in apache (I think it is necessary because I use bootstrap)
6. Create cron jobs to read regularly the weather data:
 */5 * * * *     <user> /usr/local/share/weatherradio/bin/wr_rrd_lastupdate.py 
 */5 * * * *     <user> /usr/local/share/weatherradio/bin/wr_rrd_fetch.py -s 6h
 */15 * * * *     <user> /usr/local/share/weatherradio/bin/wr_rrd_fetch.py -s 1d
 0 * * * *     <user> /usr/local/share/weatherradio/bin/wr_rrd_fetch.py -s 7d
 0 0 * * *     <user> /usr/local/share/weatherradio/bin/wr_rrd_fetch.py -s 30d

**Comment by xthestreams** [comment]
> I've spent the last weeks with developing a refurbished version of the good old Arduino based weather driver and called it Weather Radio. Its still in a beta stage, but meanwhile ready for others to be tested. It contains:
> 
> * New Arduino driver that delivers sensor data as JSON document.
> * New indi_weatherradio INDI driver that interacts with the Arduino driver and delivers weather info usable in the Observatory tab of KStars
>   main_control
> * A completely rewritten HTML based UI for the weather  - see my local weather station http://weather.openfuture.de This UI uses an RRD storage for data history and a set of scripts to create JSON documents that are read from the browser to display the charts.

Great update and the WeatherRadio device seems amazing! Trying to compile the .ino code for a DHT22 device failed with an error that I couldn't debug myself so I reverted to an older version of the code that worked great. 

For those who used Nacho's old instructions with the sensors he suggested you will want to throw those out and get the ones that Wolfgang is supporting and you will get a better result!

**Comment by sterne-jaeger** [comment]
Paul, we are on a quite old thread here, but nevertheless: what problem do you have with compiling for DHT22? I checked it, at least compiling works fine.

**Comment by xthestreams** [comment]
I figured it out - but for the sake of other stupid people like me, here's the error and the solution (which is NOT to use any of the old libraries Nacho included in the original distro).

Wolfgang's approach seems to be slightly different and instead suggests you download the libraries yourself - which is fine but resulted in a few inconsistencies - eg: the METEOtest complied and uploaded fine - the InduinoMETEO code breaks with an error related to teh DHT library. I should probably update the README to the Indiuino project to help others avoid my little mistake.

In other news, I am having trouble compiling WeatherRadio with the ESP8266 module enabled, it seems again to be a library problem but it's not so obvious which one to include (using the Arduino IDE).

Screen Shot 2020-07-22 at 8 50 50 am

**Pull request merged**
