### PR TITLE
SVBony SV305 : SDK update, temperature regulation fix, code cleaning and minor fixes

### PR DESCRIPTION
**Pull request by thx8411**
Hi,

SVBONY SDK update, fixing the SV405CC temperature regulation.

Thanks to Kakura, code cleaning and fixes.

Best regards,

Blaise

### CODE REVIEW

**Comment by knro** [comment]
Thanks, please check the build errors.

There are also some docker issues apparently that just popped up recently. Not sure why cfitsio is suddenly missing?

**Comment by thx8411** [comment]
Hi Jasem,

OK.

Weird : On my Ubuntu 20.04 laptop, I have libcfitsio.so.8, but the in Ubuntu 20.04 container, the build process is looking for the libcfitsio.so.7

Best regards,

Blaise

**Comment by knro** [comment]
Is this a docker build issue? I've seen it before and it disappeared on its own but now it's back.

**Comment by thx8411** [comment]
Hi Jasem,

<< Is this a docker build issue? >>

I think so. I tried to reproduce it on Circle CI without success. I will try to do more tests.

I can't figure where this "libfitsio.so.7" dependency  comes from...

Best regards,

Blaise

**Pull request merged**
