### PR TITLE
Fix warnings - Add build for MacOS - Reupload

### PR DESCRIPTION
**Pull request by pawel-soja**
https://github.com/indilib/indi-3rdparty/pull/384

### CODE REVIEW

**Comment by knro** [comment]
Thanks, that still ends up installing to /usr/lib.. I even tried to add in ${LIB_POSTFIX} but same results.

**Comment by pawel-soja** [comment]
Are you sure?
Make sure you run cmake in an empty directory. 
```
$ cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_LIBS=1 \
    . ~/Projects/indi-3rdparty

$ make
 ...
$ sudo make install
 ...
-- Up-to-date: /usr/include/libricohcamerasdk/ricoh_camera_sdk/hyper_operation_enable.hpp
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libRicohCameraSDKCpp.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libRicohCameraSDKCpp.so.1
-- Installing: /usr/lib/x86_64-linux-gnu/libRicohCameraSDKCpp.so.1.1.0
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libmtpricoh.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libmtpricoh.so.9
-- Installing: /usr/lib/x86_64-linux-gnu/libmtpricoh.so.9.3.0
-- Installing: /etc/udev/rules.d/95-pentax.rules
-- Installing: /etc/udev/rules.d/95-samsung.rules
 ...
$ cat ~/Projects/build/indi-3rdparty-libs/install_manifest.txt  | grep "x86.*so$"
/usr/lib/x86_64-linux-gnu/libapogee.so
/usr/lib/x86_64-linux-gnu/libASICamera2.so
/usr/lib/x86_64-linux-gnu/libEFWFilter.so
/usr/lib/x86_64-linux-gnu/libUSB2ST4Conv.so
/usr/lib/x86_64-linux-gnu/libEAFFocuser.so
/usr/lib/x86_64-linux-gnu/libatikcameras.so
/usr/lib/x86_64-linux-gnu/libflycapture.so
/usr/lib/x86_64-linux-gnu/libfishcamp.so
/usr/lib/x86_64-linux-gnu/libfli.so
/usr/lib/x86_64-linux-gnu/libgxccd.so
/usr/lib/x86_64-linux-gnu/libinovasdk.so
/usr/lib/x86_64-linux-gnu/libqhyccd.so
/usr/lib/x86_64-linux-gnu/libqsiapi.so
/usr/lib/x86_64-linux-gnu/libsbig.so
/usr/lib/x86_64-linux-gnu/libRicohCameraSDKCpp.so
/usr/lib/x86_64-linux-gnu/libmtpricoh.so
/usr/lib/x86_64-linux-gnu/libpktriggercord.so
/usr/lib/x86_64-linux-gnu/libahp_xc.so
/usr/lib/x86_64-linux-gnu/libtoupcam.so
/usr/lib/x86_64-linux-gnu/libaltaircam.so
/usr/lib/x86_64-linux-gnu/libstarshootg.so
/usr/lib/x86_64-linux-gnu/libnncam.so
/usr/lib/x86_64-linux-gnu/libmallincam.so
/usr/lib/x86_64-linux-gnu/libSVBCameraSDK.so
```

**Comment by knro** [comment]
What if you want to do it for a single library?

cmake -DCMAKE_INSTALL_PREFIX=/usr ~/Projects/indi-3rdparty/libasi/
sudo make install

**Comment by pawel-soja** [comment]
ok, magic :) I'll check it :)

**Comment by pawel-soja** [comment]
Fixed.
@knro can you check please?

**Comment by knro** [comment]
Thanks! This is good to go now from Debian side. @xsnrg Can you check if no issues over at Fedora?

**Comment by xsnrg** [comment]
I tried point the build for one of the drivers to this branch in Copr, and it was successful. I did not try them all, but do not see a reason to hold it up.

https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/build/2150237/

**Comment by pawel-soja** [comment]
Thanks Jim!

**Pull request merged**
