### PR TITLE
Update PlayerOneCamera SDK to v3.6.2

### PR DESCRIPTION
**Pull request by hiro3110i**

### CODE REVIEW

**Comment by glundby** [comment]
Regressed to stop before download second sub Player One Saturn-CSQR. Behaviour exacly like about one year ago when it was fixed. Recreate; Take more than one sub with more than 2s exposure. Every second exposure gets hung before download until timeout after about a minute. Then works for one sub...

**Comment by hiro3110i** [comment]
@glundby I tested kstars v3.7.1 stable and indi v2.0.8 on Raspberry Pi4/Ubuntu Mate 22.04.
I don't have any problems, it's working very well. Stable setup is important for daily operation.
My recommendation is Pi4/Ubuntu Mate 22.04 with kstars v3.7.1/indi v2.0.8.

I recognize some problems on Raspberry Pi5/Ubuntu 24.04.
We have to wait a little to use Pi5/Ubuntu 24.04.
PlayerOne engineers are investigating USB compatibilities of Pi5/Ubuntu 24.04.
If you want to use Pi5, you should use Ubuntu 23.10. It's working well on my side.

**Comment by knro** [comment]
Thank you @hiro3110i , how about Raspberry 5 with Debian 12 (Bookworm)?

**Comment by glundby** [comment]
Hello!

TEST WITH UBUNTU NEWEST ON LAPTOP:

I have retested on my laptop with Ubuntu and I get exactly same error namely every capture except first hangs after capture until timeout if exposure time is equal or greater than 2s. The versions of Player One library was:

Kstars 3.7.0 Stable
With Player One CCD 1.13 and SDK 3.6.1

I did sudo apt-get update and apt-get upgrade and got ubuntu 5.15.0-112

I then got Kstars build 2024-06-01T15:02:53Z

With Player One CCD 1.14 and SDK 3.6.2

Did test again with 10 sub a 10s and same error for each sub:

      Exposure time timeout. Restarting exposure

Tried two different USB cables. To prove HW and firmware I did similar test with FireCapture v2.7.14 x64 The test, 10s full frames were successful!

Regards! Gustav Olav LUNDBY

[cid:78e853e4-a389-411a-8b64-a44878c4f64e]
________________________________
Fra: Jasem Mutlaq ***@***.***>
Sendt: søndag 9. juni 2024 06:11
Til: indilib/indi-3rdparty ***@***.***>
Kopi: Gustav Olav Lundby ***@***.***>; Mention ***@***.***>
Emne: Re: [indilib/indi-3rdparty] Update PlayerOneCamera SDK to v3.6.2 (PR #922)


Thank you @hiro3110i<https://github.com/hiro3110i> , how about Raspberry 5 with Debian 12 (Bookworm)?

**Comment by glundby** [comment]
Hello!

Finally found out how to test my Saturn-C in N.I.N.A. On my Windows 11 laptop using ASCOM. Works fine!!!

Nothing wrong with my HW or cabling.

Regards! Gustav
________________________________
Fra: Jasem Mutlaq ***@***.***>
Sendt: søndag 9. juni 2024 06:11
Til: indilib/indi-3rdparty ***@***.***>
Kopi: Gustav Olav Lundby ***@***.***>; Mention ***@***.***>
Emne: Re: [indilib/indi-3rdparty] Update PlayerOneCamera SDK to v3.6.2 (PR #922)


Thank you @hiro3110i<https://github.com/hiro3110i> , how about Raspberry 5 with Debian 12 (Bookworm)?

**Comment by hiro3110i** [comment]
@knro Sorry for waiting, I had to build the latest Pi OS 64bit (Debian Bookworm) environment to test.
Saturn-C and Uranus-C could work fine on RasPi5 with Pi OS.
Dependency was a little tricky but I could build all of them (indi, indi-3rdparty, gsc and kstars) on Pi OS.
Ubuntu 24.04 for RasPi5 might have something wrong compatibilities of USB devices.

**Comment by hiro3110i** [comment]
@glundby When you say the newest Ubuntu, do you mean 24.04?
Ubuntu 24.04 might have something wrong for USB devices.
I also have problems on RasPi5 with Ubuntu 24.04.
So my suggestion is: you should use Ubuntu 22.04 or 23.10 just now.

**Pull request merged**
